apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: telepresence-db
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: telepresence-db
  template:
    metadata:
      labels:
        svc: telepresence-db
    spec:
      containers:
      - name: telepresence-db
        image: mavellol/telepresence-db
        ports:
        - name: db-port
          containerPort: 3306
      volumes:
      - name: telepresence-mysql-data
        persistentVolumeClaim:
          claimName: telepresence-mysql-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: telepresence-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/telepresence-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telepresence-mysql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: telepresence-db
spec:
  ports:
  - name: db-port
    port: 3306
    targetPort: db-port
  selector:
    svc: telepresence-db