apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence-php
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: telepresence-php
  template:
    metadata:
      labels:
        svc: telepresence-php
    spec:
      containers:
      - name: telepresence-php
        image: mavellol/telepresence-php
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
      - name: telepresence-nginx
        image: mavellol/telepresence-nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      volumes:
      - name: shared-files
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: telepresence-np
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    svc: telepresence-php